# Pre-commit hooks configuration
# Install: pre-commit install
# Run manually: pre-commit run --all-files
# Update hooks: pre-commit autoupdate

repos:
  # Go formatting
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      # Format code
      - id: go-fmt
        args: [-w]

      # Organize imports
      - id: go-imports
        args: [-w]

      # Run go vet
      # Disabled: hook has issues with directory structure
      # Use 'make vet' instead
      # - id: go-vet
      #   args: [./...]

      # Run go mod tidy
      - id: go-mod-tidy

      # Check for common mistakes
      - id: go-unit-tests
        args: [-short, -race, -timeout=5m]
        pass_filenames: false

  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      # Prevent large files from being committed
      - id: check-added-large-files
        args: [--maxkb=1000]

      # Check for merge conflicts
      - id: check-merge-conflict

      # Check YAML syntax
      - id: check-yaml
        args: [--allow-multiple-documents]

      # Check JSON syntax
      - id: check-json

      # Check TOML syntax
      - id: check-toml

      # Trim trailing whitespace
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

      # Fix end of files
      - id: end-of-file-fixer

      # Prevent committing to main
      - id: no-commit-to-branch
        args: [--branch, main, --branch, master]

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: [--baseline, .secrets.baseline]
        exclude: package.lock.json

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: [--fix]
        exclude: ^(CHANGELOG.md|CLAUDE.md|CONTRIBUTING.md|README.md|SECURITY.md|SETUP_SUMMARY.md|docs/.*\.md)$

  # Commit message linting
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.1.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--force-scope]

# Custom local hooks
  - repo: local
    hooks:
      # Run golangci-lint (use GOPATH version v1.64.8, not Homebrew v2.x)
      - id: golangci-lint
        name: golangci-lint
        entry: bash -c 'PATH="$(go env GOPATH)/bin:$PATH" golangci-lint run --fix'
        language: system
        types: [go]
        pass_filenames: false

      # Check for TODO comments without issue numbers
      - id: check-todos
        name: Check TODOs have issue numbers
        entry: bash -c 'grep -rn "TODO" --include="*.go" . | grep -v "TODO(#[0-9]" && exit 1 || exit 0'
        language: system
        pass_filenames: false
        always_run: true
